### ISSUE TITLE
About SMPL shape parameters

### ISSUE THREAD

**Issue by tszhang97** [google/aistplusplus_api#9]
Hi, thanks for your amazing dataset! I found this dataset does not contain the shape parameters of SMPL model. Also, the learning rate is set to 0 for all stages. Also, shape parameters will affect the scale optimization. So, which shape parameters should I use for visualizing the SMPL mesh?

**Comment by AmberCheng** [comment]
same quesltion

**Comment by liruilong940607** [comment]
We didn't optimize for the SMPL shape parameter. Thus you can use an all-zero vector (default) for the shape parameter. We have a variable `smpl_scaling` that controls the scale factor during optimization. Please refer to the code [here](https://github.com/google/aistplusplus_api/blob/main/demos/run_vis.py#L77) about SMPL forward kinematics. 

Note you will need to use the `smplx` library from [here](https://github.com/liruilong940607/smplx) instead of the official repo. We modified it to support the scale factor `smpl_sacling`.

**Comment by tszhang97** [comment]
Thanks for your reply.  Does this mean that this dataset cannot be used along with other SMPL datasets ( like 3DPW, moshed H36M ), because the shape of the human is defined by scale rather than shape parameters.

**Comment by liruilong940607** [comment]
It can be used to combining with others. They are all roughly on the same scale if you just skip our `sampl_scaling` factor (or set it to one). The SMPL shape parameter actually more represents the **thin/fat** of the body and it only affects the global scale (height) a bit.

**Comment by tszhang97** [comment]
Thanks for your replying. I will try setting shapes to 0.
